//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IPDAService
{
    
    System.Data.DataSet GetBarcodeInfo(string Barcode);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetBarcodeInfo", Namespace="http://tempuri.org/")]
public partial class GetBarcodeInfoRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string Barcode;
    
    public GetBarcodeInfoRequest()
    {
    }
    
    public GetBarcodeInfoRequest(string Barcode)
    {
        this.Barcode = Barcode;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetBarcodeInfoResponse", Namespace="http://tempuri.org/")]
public partial class GetBarcodeInfoResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public System.Data.DataSet GetBarcodeInfoResult;
    
    public GetBarcodeInfoResponse()
    {
    }
    
    public GetBarcodeInfoResponse(System.Data.DataSet GetBarcodeInfoResult)
    {
        this.GetBarcodeInfoResult = GetBarcodeInfoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class PDAServiceClient : Microsoft.Tools.ServiceModel.CFClientBase<IPDAService>, IPDAService
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://192.168.1.206:90/PDAService.svc");
    
    public PDAServiceClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public PDAServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private GetBarcodeInfoResponse GetBarcodeInfo(GetBarcodeInfoRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IPDAService/GetBarcodeInfo";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IPDAService/GetBarcodeInfoResponse";
        info.ResponseIsWrapped = true;
        GetBarcodeInfoResponse retVal = base.Invoke<GetBarcodeInfoRequest, GetBarcodeInfoResponse>(info, request);
        return retVal;
    }
    
    public System.Data.DataSet GetBarcodeInfo(string Barcode)
    {
        GetBarcodeInfoRequest request = new GetBarcodeInfoRequest(Barcode);
        GetBarcodeInfoResponse response = this.GetBarcodeInfo(request);
        return response.GetBarcodeInfoResult;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("http://tempuri.org/IPDAService/GetBarcodeInfo", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IPDAService/GetBarcodeInfo", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("http://tempuri.org/IPDAService/GetBarcodeInfoResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IPDAService/GetBarcodeInfoResponse", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
